services:
    # Backend PHP
    app:
        build:
            context: ./
            dockerfile: images/PHP/Dockerfile
        container_name: app-monolith
        restart: "no"
        working_dir: /var/www/
        volumes:
            - ./.:/var/www
            - ./app-monolith:/var/www/app-monolith
        depends_on:
            - db_pgsql

    nginx:
        image: nginx:1.25.1-alpine-slim
        container_name: app-monolith-nginx
        restart: "no"
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./app-monolith:/var/www/app-monolith
            - ./nginx:/etc/nginx/conf.d
    db_pgsql:
        build:
            context: ./
            dockerfile: images/PostgreSQL/Dockerfile
        container_name: app-monolith-db
        restart: "no"
        environment:
            - POSTGRES_DB=app-monolith-db
            - POSTGRES_USER=admin_db
            - POSTGRES_PASSWORD=postgresql
        ports:
            - "5432:5432"
        volumes:
            - db_pgsql:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: app-monolith-pgadmin
        restart: "no"
        environment:
            # Login pgadmin
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        volumes:
            - pgadmin_4:/var/lib/pgadmin
        depends_on:
            - db_pgsql
volumes:
    db_pgsql:
    pgadmin_4: